### ISSUE TITLE
[BUG] Spells not appearing on Magic Tab when Equipping Grimoire

### ISSUE THREAD

**Issue by StevenEvans1966** [Forien/foundryvtt-forien-armoury#50] opened 2024-09-18 15:35 UTC
Create a Grimoire add a couple of spell.  Give to Character.  Equip Grimoire. Spells do not appear on Character's Magic tab

Console Errors:

10foundry-esm.js:4621 Error: The {{select}} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or the foundry.applications.fields.createSelectInput, foundry.applications.fields.createMultiSelectElement, or foundry.applications.fields.prepareSelectOptionGroups methods.
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at ItemWfrp4e.select (foundry.js:8349:19)
    at ItemWfrp4e.c (handlebars.min.js:27:27865)
    at eval (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:23:129)
    at h (handlebars.min.js:27:25975)
    at c (handlebars.min.js:27:6943)
    at Object.<anonymous> (handlebars.min.js:27:7333)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:43:49)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at Object.h (handlebars.min.js:27:26843)
    at Object.c [as invokePartial] (handlebars.min.js:27:23141)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:140:28)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async ActorSheetWFRP4eCharacter._renderInner (foundry.js:6013:16)
    at async ActorSheetWFRP4eCharacter._renderInner (foundry.js:6583:18)
    at async ActorSheetWFRP4eCharacter._render (foundry.js:5844:19)
    at async ActorSheetWFRP4eCharacter._render (foundry.js:6572:5)
    at async ActorSheetWFRP4eCharacter._render (foundry.js:7158:5)
    at async ActorSheetWFRP4eCharacter._render (warhammer.js:5654:9)
    at async ActorSheetWFRP4eCharacter._render (wfrp4e.js:8505:5)
logCompatibilityWarning @ foundry-esm.js:4621
select @ foundry.js:8349
c @ handlebars.min.js:27
eval @ VM2238:23
h @ handlebars.min.js:27
c @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2239:43
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
h @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2046:140
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:7902
await in renderTemplate
_renderInner @ foundry.js:6013
_renderInner @ foundry.js:6583
_render @ foundry.js:5844
await in _render
_render @ foundry.js:6572
_render @ foundry.js:7158
_render @ warhammer.js:5654
_render @ wfrp4e.js:8505
render @ foundry.js:5793
🎁call_wrapped @ libWrapper-wrapper.js:534
🎁ActorSheet.prototype.render#item-piles @ libwrapper.js:50
🎁call_wrapper @ libWrapper-wrapper.js:643
🎁ActorSheet.prototype.render#0 @ libWrapper-wrapper.js:193
render @ foundry.js:10871
_onUpdateDescendantDocuments @ foundry.js:11239
_onUpdateDescendantDocuments @ foundry.js:16128
_onUpdateDescendantDocuments @ warhammer.js:4198
_onUpdateDescendantDocuments @ wfrp4e.js:15096
_dispatchDescendantDocumentEvents @ foundry.js:11159
#handleUpdateDocuments @ foundry-esm.js:56595
await in #handleUpdateDocuments
_updateDocuments @ foundry-esm.js:56473
await in _updateDocuments
update @ foundry-esm.js:12329
await in update
updateDocuments @ foundry-esm.js:11473
update @ foundry-esm.js:11584
toggleEquip @ wfrp4e.js:8423
_onItemToggle @ wfrp4e.js:9717
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2Understand this warning
2wfrp4e.js:29180 [DEPRECATION] `container.worn` is deprecated, please use `container.equipped` instead
get worn @ wfrp4e.js:29180
get worn @ wfrp4e.js:520
lookupProperty @ handlebars.min.js:27
eval @ VM2303:10
h @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2304:10
h @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2320:23
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
h @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2298:11
h @ handlebars.min.js:27
c @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2299:10
h @ handlebars.min.js:27
(anonymous) @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2300:50
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
h @ handlebars.min.js:27
c @ handlebars.min.js:27
eval @ VM2046:144
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:7902
await in renderTemplate
_renderInner @ foundry.js:6013
_renderInner @ foundry.js:6583
_render @ foundry.js:5844
await in _render
_render @ foundry.js:6572
_render @ foundry.js:7158
_render @ warhammer.js:5654
_render @ wfrp4e.js:8505
render @ foundry.js:5793
🎁call_wrapped @ libWrapper-wrapper.js:534
🎁ActorSheet.prototype.render#item-piles @ libwrapper.js:50
🎁call_wrapper @ libWrapper-wrapper.js:643
🎁ActorSheet.prototype.render#0 @ libWrapper-wrapper.js:193
render @ foundry.js:10871
_onUpdateDescendantDocuments @ foundry.js:11239
_onUpdateDescendantDocuments @ foundry.js:16128
_onUpdateDescendantDocuments @ warhammer.js:4198
_onUpdateDescendantDocuments @ wfrp4e.js:15096
_dispatchDescendantDocumentEvents @ foundry.js:11159
#handleUpdateDocuments @ foundry-esm.js:56595
await in #handleUpdateDocuments
_updateDocuments @ foundry-esm.js:56473
await in _updateDocuments
update @ foundry-esm.js:12329
await in update
updateDocuments @ foundry-esm.js:11473
update @ foundry-esm.js:11584
toggleEquip @ wfrp4e.js:8423
_onItemToggle @ wfrp4e.js:9717
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2Understand this warning
foundry-esm.js:4621 Error: The {{select}} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or the foundry.applications.fields.createSelectInput, foundry.applications.fields.createMultiSelectElement, or foundry.applications.fields.prepareSelectOptionGroups methods.
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at Object.logCompatibilityWarning (foundry-esm.js:4609:19)
    at Object.select (foundry.js:8349:19)
    at Object.c (handlebars.min.js:27:27865)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), <anonymous>:29:129)
    at c (handlebars.min.js:27:23534)
    at d (handlebars.min.js:27:23849)
    at e (handlebars.min.js:28:30886)
    at renderTemplate (foundry.js:7902:10)
    at async GrimoireSheet._renderInner (foundry.js:6013:16)
    at async GrimoireSheet._renderInner (foundry.js:6583:18)
    at async GrimoireSheet._render (foundry.js:5844:19)
    at async GrimoireSheet._render (foundry.js:6572:5)
    at async GrimoireSheet._render (foundry.js:7158:5)
    at async GrimoireSheet._render (warhammer.js:5756:9)
    at async GrimoireSheet._render (wfrp4e.js:12312:5)
logCompatibilityWarning @ foundry-esm.js:4621
select @ foundry.js:8349
c @ handlebars.min.js:27
eval @ VM2454:29
c @ handlebars.min.js:27
d @ handlebars.min.js:27
e @ handlebars.min.js:28
renderTemplate @ foundry.js:7902
await in renderTemplate
_renderInner @ foundry.js:6013
_renderInner @ foundry.js:6583
_render @ foundry.js:5844
await in _render
_render @ foundry.js:6572
_render @ foundry.js:7158
_render @ warhammer.js:5756
_render @ wfrp4e.js:12312
render @ foundry.js:5793
render @ foundry.js:10871
_onUpdate @ foundry.js:11064
_onUpdate @ warhammer.js:4079
_onUpdate @ warhammer.js:4478
_onUpdate @ wfrp4e.js:50
(anonymous) @ foundry-esm.js:56583
(anonymous) @ foundry-esm.js:56590
#handleUpdateDocuments @ foundry-esm.js:56590
await in #handleUpdateDocuments
_updateDocuments @ foundry-esm.js:56473
await in _updateDocuments
update @ foundry-esm.js:12329
await in update
updateDocuments @ foundry-esm.js:11473
update @ foundry-esm.js:11584
toggleEquip @ wfrp4e.js:8423
_onItemToggle @ wfrp4e.js:9717
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2Understand this warning
wfrp4e.js:658 wfrp4e | Sound file not found for context: {item: ItemWfrp4e, action: 'equip', outcome: true}
(anonymous) @ wfrp4e.js:658
Promise.then
PlayContextAudio @ wfrp4e.js:656
_onItemToggle @ wfrp4e.js:9719
await in _onItemToggle
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2Understand this warning

**Comment by Forien** [comment] 2024-09-18 15:43
> Create a Grimoire add a couple of spell. Give to Character. Equip Grimoire. Spells do not appear on Character's Magic tab

Check your settings, grimoire's language and your character's skills and talents.

> Console Errors:
> 
> 10foundry-esm.js:4621 Error: The {{select}} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or the foundry.applications.fields.createSelectInput, foundry.applications.fields.createMultiSelectElement, or foundry.applications.fields.prepareSelectOptionGroups methods. Deprecated since Version 12 Backwards-compatible support will be removed in Version 14 at Object.logCompatibilityWarning (foundry-esm.js:4609:19) at ItemWfrp4e.select (foundry.js:8349:19) at ItemWfrp4e.c (handlebars.min.js:27:27865) at eval (eval at createFunctionContext (handlebars.min.js:29:10011), :23:129) at h (handlebars.min.js:27:25975) at c (handlebars.min.js:27:6943) at Object. (handlebars.min.js:27:7333) at Object.c (handlebars.min.js:27:27865) at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), :43:49) at c (handlebars.min.js:27:23534) at d (handlebars.min.js:27:23849) at e (handlebars.min.js:28:30886) at Object.h (handlebars.min.js:27:26843) at Object.c [as invokePartial] (handlebars.min.js:27:23141) at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), :140:28) at c (handlebars.min.js:27:23534) at d (handlebars.min.js:27:23849) at e (handlebars.min.js:28:30886) at renderTemplate (foundry.js:7902:10) at async ActorSheetWFRP4eCharacter._renderInner (foundry.js:6013:16) at async ActorSheetWFRP4eCharacter._renderInner (foundry.js:6583:18) at async ActorSheetWFRP4eCharacter._render (foundry.js:5844:19) at async ActorSheetWFRP4eCharacter._render (foundry.js:6572:5) at async ActorSheetWFRP4eCharacter._render (foundry.js:7158:5) at async ActorSheetWFRP4eCharacter._render (warhammer.js:5654:9) at async ActorSheetWFRP4eCharacter._render (wfrp4e.js:8505:5) logCompatibilityWarning @ foundry-esm.js:4621 select @ foundry.js:8349 c @ handlebars.min.js:27 eval @ VM2238:23 h @ handlebars.min.js:27 c @ handlebars.min.js:27 (anonymous) @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2239:43 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 h @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2046:140 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 renderTemplate @ foundry.js:7902 await in renderTemplate _renderInner @ foundry.js:6013 _renderInner @ foundry.js:6583 _render @ foundry.js:5844 await in _render _render @ foundry.js:6572 _render @ foundry.js:7158 _render @ warhammer.js:5654 _render @ wfrp4e.js:8505 render @ foundry.js:5793 🎁call_wrapped @ libWrapper-wrapper.js:534 🎁ActorSheet.prototype.render#item-piles @ libwrapper.js:50 🎁call_wrapper @ libWrapper-wrapper.js:643 🎁ActorSheet.prototype.render#0 @ libWrapper-wrapper.js:193 render @ foundry.js:10871 _onUpdateDescendantDocuments @ foundry.js:11239 _onUpdateDescendantDocuments @ foundry.js:16128 _onUpdateDescendantDocuments @ warhammer.js:4198 _onUpdateDescendantDocuments @ wfrp4e.js:15096 _dispatchDescendantDocumentEvents @ foundry.js:11159 #handleUpdateDocuments @ foundry-esm.js:56595 await in #handleUpdateDocuments _updateDocuments @ foundry-esm.js:56473 await in _updateDocuments update @ foundry-esm.js:12329 await in update updateDocuments @ foundry-esm.js:11473 update @ foundry-esm.js:11584 toggleEquip @ wfrp4e.js:8423 _onItemToggle @ wfrp4e.js:9717 dispatch @ jquery.min.js:2 v.handle @ jquery.min.js:2Understand this warning 2wfrp4e.js:29180 [DEPRECATION] `container.worn` is deprecated, please use `container.equipped` instead get worn @ wfrp4e.js:29180 get worn @ wfrp4e.js:520 lookupProperty @ handlebars.min.js:27 eval @ VM2303:10 h @ handlebars.min.js:27 (anonymous) @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2304:10 h @ handlebars.min.js:27 (anonymous) @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2320:23 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 h @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2298:11 h @ handlebars.min.js:27 c @ handlebars.min.js:27 (anonymous) @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2299:10 h @ handlebars.min.js:27 (anonymous) @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2300:50 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 h @ handlebars.min.js:27 c @ handlebars.min.js:27 eval @ VM2046:144 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 renderTemplate @ foundry.js:7902 await in renderTemplate _renderInner @ foundry.js:6013 _renderInner @ foundry.js:6583 _render @ foundry.js:5844 await in _render _render @ foundry.js:6572 _render @ foundry.js:7158 _render @ warhammer.js:5654 _render @ wfrp4e.js:8505 render @ foundry.js:5793 🎁call_wrapped @ libWrapper-wrapper.js:534 🎁ActorSheet.prototype.render#item-piles @ libwrapper.js:50 🎁call_wrapper @ libWrapper-wrapper.js:643 🎁ActorSheet.prototype.render#0 @ libWrapper-wrapper.js:193 render @ foundry.js:10871 _onUpdateDescendantDocuments @ foundry.js:11239 _onUpdateDescendantDocuments @ foundry.js:16128 _onUpdateDescendantDocuments @ warhammer.js:4198 _onUpdateDescendantDocuments @ wfrp4e.js:15096 _dispatchDescendantDocumentEvents @ foundry.js:11159 #handleUpdateDocuments @ foundry-esm.js:56595 await in #handleUpdateDocuments _updateDocuments @ foundry-esm.js:56473 await in _updateDocuments update @ foundry-esm.js:12329 await in update updateDocuments @ foundry-esm.js:11473 update @ foundry-esm.js:11584 toggleEquip @ wfrp4e.js:8423 _onItemToggle @ wfrp4e.js:9717 dispatch @ jquery.min.js:2 v.handle @ jquery.min.js:2Understand this warning foundry-esm.js:4621 Error: The {{select}} handlebars helper is deprecated in favor of using the {{selectOptions}} helper or the foundry.applications.fields.createSelectInput, foundry.applications.fields.createMultiSelectElement, or foundry.applications.fields.prepareSelectOptionGroups methods. Deprecated since Version 12 Backwards-compatible support will be removed in Version 14 at Object.logCompatibilityWarning (foundry-esm.js:4609:19) at Object.select (foundry.js:8349:19) at Object.c (handlebars.min.js:27:27865) at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:10011), :29:129) at c (handlebars.min.js:27:23534) at d (handlebars.min.js:27:23849) at e (handlebars.min.js:28:30886) at renderTemplate (foundry.js:7902:10) at async GrimoireSheet._renderInner (foundry.js:6013:16) at async GrimoireSheet._renderInner (foundry.js:6583:18) at async GrimoireSheet._render (foundry.js:5844:19) at async GrimoireSheet._render (foundry.js:6572:5) at async GrimoireSheet._render (foundry.js:7158:5) at async GrimoireSheet._render (warhammer.js:5756:9) at async GrimoireSheet._render (wfrp4e.js:12312:5) logCompatibilityWarning @ foundry-esm.js:4621 select @ foundry.js:8349 c @ handlebars.min.js:27 eval @ VM2454:29 c @ handlebars.min.js:27 d @ handlebars.min.js:27 e @ handlebars.min.js:28 renderTemplate @ foundry.js:7902 await in renderTemplate _renderInner @ foundry.js:6013 _renderInner @ foundry.js:6583 _render @ foundry.js:5844 await in _render _render @ foundry.js:6572 _render @ foundry.js:7158 _render @ warhammer.js:5756 _render @ wfrp4e.js:12312 render @ foundry.js:5793 render @ foundry.js:10871 _onUpdate @ foundry.js:11064 _onUpdate @ warhammer.js:4079 _onUpdate @ warhammer.js:4478 _onUpdate @ wfrp4e.js:50 (anonymous) @ foundry-esm.js:56583 (anonymous) @ foundry-esm.js:56590 #handleUpdateDocuments @ foundry-esm.js:56590 await in #handleUpdateDocuments _updateDocuments @ foundry-esm.js:56473 await in _updateDocuments update @ foundry-esm.js:12329 await in update updateDocuments @ foundry-esm.js:11473 update @ foundry-esm.js:11584 toggleEquip @ wfrp4e.js:8423 _onItemToggle @ wfrp4e.js:9717 dispatch @ jquery.min.js:2 v.handle @ jquery.min.js:2Understand this warning wfrp4e.js:658 wfrp4e | Sound file not found for context: {item: ItemWfrp4e, action: 'equip', outcome: true} (anonymous) @ wfrp4e.js:658 Promise.then PlayContextAudio @ wfrp4e.js:656 _onItemToggle @ wfrp4e.js:9719 await in _onItemToggle dispatch @ jquery.min.js:2 v.handle @ jquery.min.js:2Understand this warning

unrelated, also duplicate of #49 (also hard to read without formatting and it not being a screenshot)

**Closed** 2024-09-20 15:29 UTC
Labels: bug
